interfaces = []
exclude = [
    "**/*__pycache__",
    "**/*egg-info",
    "**/docs",
    "**/tests",
    "**/venv",
]
source_roots = [
    ".",
]

[[modules ]]
path = "src.logger"
depends_on = []

[[modules ]]
path = "src.metrics"
depends_on = ["src.logger", "src.utils", "src.artifacts", "src.storage"]

[[modules ]]
path = "src.artifacts"
depends_on = ["src.metrics", "src.logger", "src.utils", "src.settings", "src.storage"]

[[modules ]]
path = "src.storage"
depends_on = ["src.artifacts", "src.aws", "src.logger", "src.settings"]

[[modules ]]
path = "src.settings"
depends_on = []

[[modules ]]
path = "src.utils"
depends_on = ["src.logger", "src.settings", "src.aws"]

[[modules ]]
path = "src.auth"
depends_on = ["src.utils", "src.logger"]

[[modules ]]
path = "src.aws"
depends_on = ["src.settings"]
